version: '3.5'
services:

  nnb-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: bash -c "npm install && npm run dev"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/dist
    ports:
      - "3000:3000"
